# Generated by Django 5.1.4 on 2025-01-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, verbose_name='شماره تلفن'),
        ),
    ]
