# Generated by Django 5.1.4 on 2025-01-12 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_module', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
    ]
